name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]

    steps:
    - name: Checkout GitHub sources
      uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/io/aklivity/zilla
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: ./mvnw -B -U -nsu -Ddocker.logStdout -Ddocker.verbose install jacoco:report-aggregate
    - name: Archive zip
      run: |
        cd runtime/binding-http-kafka/
        tar -czvf target.tar.gz target
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-artifact
        path: runtime/binding-http-kafka/target.tar.gz
        retention-days: 1
